### ISSUE TITLE
[Feature Request] Allow customizing the space title

### ISSUE THREAD

**Issue by felladrin** [JacobLinCool/huggingface-sync#15]
Thank you for creating and sharing this GitHub Action!

One option that I missed is to set a custom title for the space.
Currently, the repository name is being used as the title, which is not always ideal.
https://github.com/JacobLinCool/huggingface-sync/blob/0e40797c82e0484915e5848d3ee4bc3be6b6af7a/src/index.ts#L68

Would it be possible to add this feature? If you're currently unable to work on it, please let me know, and I'll be happy to open a pull request for it.

Thank you again for your work!

**Comment by JacobLinCool** [comment]
Hello @felladrin,

I've added the `title` option based on your suggestion. Please try [v1.1.0](https://github.com/JacobLinCool/huggingface-sync/releases/tag/v1.1.0)!

**Comment by felladrin** [comment]
Thank you! Will try it!

By the way, [they've just added a new field](https://huggingface.co/posts/victor/718473545021746) `short_description` that allows adding a description that is displayed at the bottom of the sapce-card! Would you like me to open a new issue for requesting the addition of this field?

**Comment by felladrin** [comment]
I'd also like to request the addition of the `header` field, which seems to be undocumented, but it works like in [this space](https://huggingface.co/spaces/julien-c/observable-huggingface/blob/main/README.md).

When there's no `header` defined, we see the space header like this:
<img width="1297" alt="image" src="https://github.com/JacobLinCool/huggingface-sync/assets/418083/66de6d4d-ad8c-4a6c-b481-5cbf058f6539">

But when `header: mini` is set, it displays the header like this:
<img width="1284" alt="image" src="https://github.com/JacobLinCool/huggingface-sync/assets/418083/81fa4ad9-9bbe-424f-a831-cbcdd29667f2">
