### ISSUE TITLE
[Feature Request] Addition of the fields `short_description` and `header`

### ISSUE THREAD

**Issue by felladrin** [JacobLinCool/huggingface-sync#18]
HuggingFace [recently added a new `short_description` field](https://huggingface.co/posts/victor/718473545021746) that allows adding a description that is displayed at the bottom of the sapce-card.

And they have also a `header` field, which can minimize the header bar, like in [this space](https://huggingface.co/spaces/julien-c/observable-huggingface/blob/main/README.md).

When there's no `header` defined, we see the space header like this:
<img width="1297" alt="image" src="https://github.com/JacobLinCool/huggingface-sync/assets/418083/66de6d4d-ad8c-4a6c-b481-5cbf058f6539">

But when `header: mini` is set, it displays the header like this:
<img width="1284" alt="image" src="https://github.com/JacobLinCool/huggingface-sync/assets/418083/81fa4ad9-9bbe-424f-a831-cbcdd29667f2">

Would you consider adding those two fields as options for the GitHub action?

**Comment by JacobLinCool** [comment]
Hello @felladrin 

Thanks for the suggestions and feel free to try [v1.2.0](https://github.com/JacobLinCool/huggingface-sync/releases/tag/v1.2.0)! Which supports almost all space parameters including `short_description` and `header`.

I've also added `configuration` as a new input parameter that can read the configuration values from a YAML file.

**Comment by felladrin** [comment]
It's working perfectly! And the new `configuration` parameter is a great addition! 🎉 
Thank you!
